tasks:
  listLicenses:
    action: !listLicenses
      settings: ${pluginSettings}
  checkFileHeaders:
    action: !checkFileHeaders
      sources: ${module.kotlinJavaSources}
      settings: ${pluginSettings.headerSettings}
  updateFileHeaders:
    action: !updateFileHeaders
      sources: ${module.kotlinJavaSources}
      settings: ${pluginSettings.headerSettings}
  removeFileHeaders:
    action: !removeFileHeaders
      sources: ${module.kotlinJavaSources}
  collectThirdParty:
    action: !collectThirdPartyLicenses
      compileDependencies: ${module.compileClasspath}
      runtimeDependencies: ${module.runtimeClasspath}
      reportFile: ${taskOutputDir}/thirdPartyLicenses.txt